/* This file was generated by SableCC (http://www.sablecc.org/). */
package portugol.lexer;

import java.io.*;
import portugol.node.*;

@SuppressWarnings("nls")
public class Lexer {

    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in) {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;

            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }

            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }

    public Lexer(@SuppressWarnings("hiding") IPushbackReader in) {
        this.in = in;
    }

    public Token peek() throws LexerException, IOException {
        while (this.token == null) {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException {
        while (this.token == null) {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding")
        int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding")
        int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while (true) {
            int c = getChar();

            if (c != -1) {
                switch (c) {
                    case 10:
                        if (this.cr) {
                            this.cr = false;
                        } else {
                            this.line++;
                            this.pos = 0;
                        }
                        break;
                    case 13:
                        this.line++;
                        this.pos = 0;
                        this.cr = true;
                        break;
                    default:
                        this.pos++;
                        this.cr = false;
                        break;
                }

                this.text.append((char) c);

                do {
                    int oldState = (dfa_state < -1) ? (-2 - dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 = gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while (low <= high) {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if (c < tmp2[0]) {
                            high = middle - 1;
                        } else if (c > tmp2[1]) {
                            low = middle + 1;
                        } else {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                } while (dfa_state < -1);
            } else {
                dfa_state = -1;
            }

            if (dfa_state >= 0) {
                if (accept[dfa_state] != -1) {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            } else {
                if (accept_state != -1) {
                    switch (accept_token) {
                        case 0: {
                            @SuppressWarnings("hiding")
                            Token token = new0(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 1: {
                            @SuppressWarnings("hiding")
                            Token token = new1(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 2: {
                            @SuppressWarnings("hiding")
                            Token token = new2(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 3: {
                            @SuppressWarnings("hiding")
                            Token token = new3(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 4: {
                            @SuppressWarnings("hiding")
                            Token token = new4(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 5: {
                            @SuppressWarnings("hiding")
                            Token token = new5(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 6: {
                            @SuppressWarnings("hiding")
                            Token token = new6(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 7: {
                            @SuppressWarnings("hiding")
                            Token token = new7(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 8: {
                            @SuppressWarnings("hiding")
                            Token token = new8(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 9: {
                            @SuppressWarnings("hiding")
                            Token token = new9(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 10: {
                            @SuppressWarnings("hiding")
                            Token token = new10(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 11: {
                            @SuppressWarnings("hiding")
                            Token token = new11(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 12: {
                            @SuppressWarnings("hiding")
                            Token token = new12(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 13: {
                            @SuppressWarnings("hiding")
                            Token token = new13(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 14: {
                            @SuppressWarnings("hiding")
                            Token token = new14(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 15: {
                            @SuppressWarnings("hiding")
                            Token token = new15(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 16: {
                            @SuppressWarnings("hiding")
                            Token token = new16(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 17: {
                            @SuppressWarnings("hiding")
                            Token token = new17(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 18: {
                            @SuppressWarnings("hiding")
                            Token token = new18(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 19: {
                            @SuppressWarnings("hiding")
                            Token token = new19(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 20: {
                            @SuppressWarnings("hiding")
                            Token token = new20(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 21: {
                            @SuppressWarnings("hiding")
                            Token token = new21(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 22: {
                            @SuppressWarnings("hiding")
                            Token token = new22(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 23: {
                            @SuppressWarnings("hiding")
                            Token token = new23(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 24: {
                            @SuppressWarnings("hiding")
                            Token token = new24(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 25: {
                            @SuppressWarnings("hiding")
                            Token token = new25(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 26: {
                            @SuppressWarnings("hiding")
                            Token token = new26(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 27: {
                            @SuppressWarnings("hiding")
                            Token token = new27(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 28: {
                            @SuppressWarnings("hiding")
                            Token token = new28(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 29: {
                            @SuppressWarnings("hiding")
                            Token token = new29(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 30: {
                            @SuppressWarnings("hiding")
                            Token token = new30(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 31: {
                            @SuppressWarnings("hiding")
                            Token token = new31(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 32: {
                            @SuppressWarnings("hiding")
                            Token token = new32(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 33: {
                            @SuppressWarnings("hiding")
                            Token token = new33(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 34: {
                            @SuppressWarnings("hiding")
                            Token token = new34(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 35: {
                            @SuppressWarnings("hiding")
                            Token token = new35(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 36: {
                            @SuppressWarnings("hiding")
                            Token token = new36(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 37: {
                            @SuppressWarnings("hiding")
                            Token token = new37(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 38: {
                            @SuppressWarnings("hiding")
                            Token token = new38(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 39: {
                            @SuppressWarnings("hiding")
                            Token token = new39(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 40: {
                            @SuppressWarnings("hiding")
                            Token token = new40(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 41: {
                            @SuppressWarnings("hiding")
                            Token token = new41(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 42: {
                            @SuppressWarnings("hiding")
                            Token token = new42(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 43: {
                            @SuppressWarnings("hiding")
                            Token token = new43(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 44: {
                            @SuppressWarnings("hiding")
                            Token token = new44(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 45: {
                            @SuppressWarnings("hiding")
                            Token token = new45(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 46: {
                            @SuppressWarnings("hiding")
                            Token token = new46(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 47: {
                            @SuppressWarnings("hiding")
                            Token token = new47(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 48: {
                            @SuppressWarnings("hiding")
                            Token token = new48(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 49: {
                            @SuppressWarnings("hiding")
                            Token token = new49(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 50: {
                            @SuppressWarnings("hiding")
                            Token token = new50(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 51: {
                            @SuppressWarnings("hiding")
                            Token token = new51(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 52: {
                            @SuppressWarnings("hiding")
                            Token token = new52(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 53: {
                            @SuppressWarnings("hiding")
                            Token token = new53(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 54: {
                            @SuppressWarnings("hiding")
                            Token token = new54(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 55: {
                            @SuppressWarnings("hiding")
                            Token token = new55(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 56: {
                            @SuppressWarnings("hiding")
                            Token token = new56(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 57: {
                            @SuppressWarnings("hiding")
                            Token token = new57(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 58: {
                            @SuppressWarnings("hiding")
                            Token token = new58(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 59: {
                            @SuppressWarnings("hiding")
                            Token token = new59(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 60: {
                            @SuppressWarnings("hiding")
                            Token token = new60(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 61: {
                            @SuppressWarnings("hiding")
                            Token token = new61(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 62: {
                            @SuppressWarnings("hiding")
                            Token token = new62(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 63: {
                            @SuppressWarnings("hiding")
                            Token token = new63(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 64: {
                            @SuppressWarnings("hiding")
                            Token token = new64(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 0:
                                    state = State.NORMAL;
                                    break;
                            }
                            return token;
                        }
                        case 65: {
                            @SuppressWarnings("hiding")
                            Token token = new65(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 1:
                                    state = State.COMENTARIO;
                                    break;
                                case 0:
                                    state = State.COMENTARIO;
                                    break;
                            }
                            return token;
                        }
                        case 66: {
                            @SuppressWarnings("hiding")
                            Token token = new66(
                                    getText(accept_length),
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 1:
                                    state = State.COMENTARIO;
                                    break;
                            }
                            return token;
                        }
                        case 67: {
                            @SuppressWarnings("hiding")
                            Token token = new67(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 1:
                                    state = State.COMENTARIO;
                                    break;
                            }
                            return token;
                        }
                        case 68: {
                            @SuppressWarnings("hiding")
                            Token token = new68(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 1:
                                    state = State.COMENTARIO;
                                    break;
                            }
                            return token;
                        }
                        case 69: {
                            @SuppressWarnings("hiding")
                            Token token = new69(
                                    start_line + 1,
                                    start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch (state.id()) {
                                case 1:
                                    state = State.COMENTARIO;
                                    break;
                            }
                            return token;
                        }
                    }
                } else {
                    if (this.text.length() > 0) {
                        throw new LexerException(
                                new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                                "[" + (start_line + 1) + "," + (start_pos + 1) + "]"
                                + " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding")
                    EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TPrograma(line, pos);
    }

    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TConst(line, pos);
    }

    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TVar(line, pos);
    }

    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TEscreva(line, pos);
    }

    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TLer(line, pos);
    }

    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TInteiro(line, pos);
    }

    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TReal(line, pos);
    }

    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TChar(line, pos);
    }

    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TDiv(line, pos);
    }

    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TSe(line, pos);
    }

    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TEntao(line, pos);
    }

    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TFimSe(text, line, pos);
    }

    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TSenao(line, pos);
    }

    Token new13(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TFimSenao(text, line, pos);
    }

    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TFaca(line, pos);
    }

    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TAte(line, pos);
    }

    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TEnquanto(line, pos);
    }

    Token new17(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TFimEnquanto(text, line, pos);
    }

    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TRepita(line, pos);
    }

    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TPara(line, pos);
    }

    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TDe(line, pos);
    }

    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TPasso(line, pos);
    }

    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TPare(line, pos);
    }

    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TContinue(line, pos);
    }

    Token new24(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TFimPara(text, line, pos);
    }

    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TEscolha(line, pos);
    }

    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TCaso(line, pos);
    }

    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TPadrao(line, pos);
    }

    Token new28(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TFimEscolha(text, line, pos);
    }

    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TInicio(line, pos);
    }

    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TFim(line, pos);
    }

    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TMais(line, pos);
    }

    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TMenos(line, pos);
    }

    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TProduto(line, pos);
    }

    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TDivisao(line, pos);
    }

    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TIncremento(line, pos);
    }

    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TDecremento(line, pos);
    }

    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TAtribuicao(line, pos);
    }

    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TVirgula(line, pos);
    }

    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TDoisPts(line, pos);
    }

    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TPtVirg(line, pos);
    }

    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TPt(line, pos);
    }

    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TAbreParantes(line, pos);
    }

    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TFechaParentes(line, pos);
    }

    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TAbreChave(line, pos);
    }

    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TFechaChave(line, pos);
    }

    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TAbreColchete(line, pos);
    }

    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TFechaColchete(line, pos);
    }

    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TAspasSp(text, line, pos);
    }

    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TAspasDp(text, line, pos);
    }

    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TXor(line, pos);
    }

    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TOu(line, pos);
    }

    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TNao(line, pos);
    }

    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TE(line, pos);
    }

    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TIgual(line, pos);
    }

    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TDiferente(line, pos);
    }

    Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TMaior(line, pos);
    }

    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TMenor(line, pos);
    }

    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TMaiorIgual(line, pos);
    }

    Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TMenorIgual(line, pos);
    }

    Token new60(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TIdentificador(text, line, pos);
    }

    Token new61(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TNumInt(text, line, pos);
    }

    Token new62(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TNumReal(text, line, pos);
    }

    Token new63(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TEspaco(text, line, pos);
    }

    Token new64(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TComentLinha(text, line, pos);
    }

    Token new65(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TComentAninhado(line, pos);
    }

    Token new66(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TComentEscopo(text, line, pos);
    }

    Token new67(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TComentEstrela(line, pos);
    }

    Token new68(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TComentBarra(line, pos);
    }

    Token new69(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) {
        return new TComentFim(line, pos);
    }

    private int getChar() throws IOException {
        if (this.eof) {
            return -1;
        }

        int result = this.in.read();

        if (result == -1) {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException {
        int length = this.text.length();
        for (int i = length - 1; i >= acceptLength; i--) {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException {
        @SuppressWarnings("hiding")
        String text = token.getText();
        int length = text.length();

        for (int i = length - 1; i >= 0; i--) {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength) {
        StringBuffer s = new StringBuffer(acceptLength);
        for (int i = 0; i < acceptLength; i++) {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
    /*  {
     { // NORMAL
     {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {34, 34, 5}, {39, 39, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {58, 58, 16}, {59, 59, 17}, {60, 60, 18}, {61, 61, 19}, {62, 62, 20}, {65, 90, 21}, {91, 91, 22}, {93, 93, 23}, {95, 95, 24}, {97, 97, 25}, {98, 98, 26}, {99, 99, 27}, {100, 100, 28}, {101, 101, 29}, {102, 102, 30}, {103, 104, 26}, {105, 105, 31}, {106, 107, 26}, {108, 108, 32}, {109, 109, 26}, {110, 110, 33}, {111, 111, 34}, {112, 112, 35}, {113, 113, 26}, {114, 114, 36}, {115, 115, 37}, {116, 117, 26}, {118, 118, 38}, {119, 119, 26}, {120, 120, 39}, {121, 122, 26}, {123, 123, 40}, {125, 125, 41}, },
     {{9, 32, -2}, },
     {{9, 32, -2}, },
     {{9, 9, 1}, {10, 10, 42}, {13, 32, -2}, },
     {{9, 32, -2}, },
     {},
     {},
     {},
     {},
     {},
     {{43, 43, 43}, },
     {},
     {{45, 45, 44}, },
     {},
     {{42, 42, 45}, {47, 47, 46}, },
     {{46, 46, 47}, {48, 57, 15}, },
     {},
     {},
     {{45, 45, 48}, {61, 61, 49}, {62, 62, 50}, },
     {},
     {{61, 61, 51}, },
     {{48, 57, 52}, {65, 90, 53}, {95, 95, 54}, {97, 122, 55}, },
     {},
     {},
     {{48, 122, -23}, },
     {{48, 95, -23}, {97, 115, 55}, {116, 116, 56}, {117, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 95, -23}, {97, 97, 57}, {98, 103, 55}, {104, 104, 58}, {105, 110, 55}, {111, 111, 59}, {112, 122, 55}, },
     {{48, 95, -23}, {97, 100, 55}, {101, 101, 60}, {102, 104, 55}, {105, 105, 61}, {106, 122, 55}, },
     {{48, 95, -23}, {97, 109, 55}, {110, 110, 62}, {111, 114, 55}, {115, 115, 63}, {116, 122, 55}, },
     {{48, 95, -23}, {97, 97, 64}, {98, 104, 55}, {105, 105, 65}, {106, 122, 55}, },
     {{48, 109, -31}, {110, 110, 66}, {111, 122, 55}, },
     {{48, 100, -30}, {101, 101, 67}, {102, 122, 55}, },
     {{48, 95, -23}, {97, 97, 68}, {98, 122, 55}, },
     {{48, 95, -23}, {97, 116, 55}, {117, 117, 69}, {118, 122, 55}, },
     {{48, 95, -23}, {97, 97, 70}, {98, 113, 55}, {114, 114, 71}, {115, 122, 55}, },
     {{48, 100, -30}, {101, 101, 72}, {102, 122, 55}, },
     {{48, 100, -30}, {101, 101, 73}, {102, 122, 55}, },
     {{48, 95, -23}, {97, 97, 74}, {98, 122, 55}, },
     {{48, 95, -23}, {97, 110, 55}, {111, 111, 75}, {112, 122, 55}, },
     {},
     {},
     {{9, 32, -2}, },
     {},
     {},
     {},
     {{0, 9, 76}, {11, 12, 76}, {14, 65535, 76}, },
     {{48, 57, 77}, },
     {},
     {},
     {},
     {},
     {{48, 122, -23}, },
     {{48, 122, -23}, },
     {{48, 122, -23}, },
     {{48, 122, -23}, },
     {{48, 100, -30}, {101, 101, 78}, {102, 122, 55}, },
     {{48, 95, -23}, {97, 114, 55}, {115, 115, 79}, {116, 122, 55}, },
     {{48, 95, -23}, {97, 97, 80}, {98, 122, 55}, },
     {{48, 109, -31}, {110, 110, 81}, {111, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 95, -23}, {97, 117, 55}, {118, 118, 82}, {119, 122, 55}, },
     {{48, 95, -23}, {97, 112, 55}, {113, 113, 83}, {114, 115, 55}, {116, 116, 84}, {117, 122, 55}, },
     {{48, 95, -23}, {97, 98, 55}, {99, 99, 85}, {100, 122, 55}, },
     {{48, 98, -65}, {99, 99, 86}, {100, 122, 55}, },
     {{48, 95, -23}, {97, 108, 55}, {109, 109, 87}, {110, 122, 55}, },
     {{48, 95, -23}, {97, 104, 55}, {105, 105, 88}, {106, 115, 55}, {116, 116, 89}, {117, 122, 55}, },
     {{48, 95, -23}, {97, 113, 55}, {114, 114, 90}, {115, 122, 55}, },
     {{48, 110, -41}, {111, 111, 91}, {112, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 95, -23}, {97, 99, 55}, {100, 100, 92}, {101, 113, 55}, {114, 114, 93}, {115, 115, 94}, {116, 122, 55}, },
     {{48, 110, -41}, {111, 111, 95}, {112, 122, 55}, },
     {{48, 95, -23}, {97, 97, 96}, {98, 111, 55}, {112, 112, 97}, {113, 122, 55}, },
     {{48, 109, -31}, {110, 110, 98}, {111, 122, 55}, },
     {{48, 113, -69}, {114, 114, 99}, {115, 122, 55}, },
     {{48, 113, -69}, {114, 114, 100}, {115, 122, 55}, },
     {{0, 65535, -48}, },
     {{48, 57, 77}, },
     {{48, 122, -23}, },
     {{48, 110, -41}, {111, 111, 101}, {112, 122, 55}, },
     {{48, 113, -69}, {114, 114, 102}, {115, 122, 55}, },
     {{48, 114, -59}, {115, 115, 103}, {116, 116, 104}, {117, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 116, -36}, {117, 117, 105}, {118, 122, 55}, },
     {{48, 95, -23}, {97, 97, 106}, {98, 122, 55}, },
     {{48, 110, -41}, {111, 111, 107}, {112, 113, 55}, {114, 114, 108}, {115, 122, 55}, },
     {{48, 95, -23}, {97, 97, 109}, {98, 122, 55}, },
     {{32, 32, 110}, {48, 122, -23}, },
     {{48, 98, -65}, {99, 99, 111}, {100, 122, 55}, },
     {{48, 100, -30}, {101, 101, 112}, {102, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 122, -23}, },
     {{48, 113, -69}, {114, 114, 113}, {115, 122, 55}, },
     {{48, 95, -23}, {97, 97, 114}, {98, 100, 55}, {101, 101, 115}, {102, 122, 55}, },
     {{48, 114, -59}, {115, 115, 116}, {116, 122, 55}, },
     {{48, 95, -23}, {97, 102, 55}, {103, 103, 117}, {104, 122, 55}, },
     {{48, 95, -23}, {97, 107, 55}, {108, 108, 118}, {109, 122, 55}, },
     {{48, 104, -68}, {105, 105, 119}, {106, 122, 55}, },
     {{48, 95, -23}, {97, 97, 120}, {98, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 122, -23}, },
     {{48, 122, -23}, },
     {{48, 122, -23}, },
     {{48, 115, -27}, {116, 116, 121}, {117, 122, 55}, },
     {{48, 104, -68}, {105, 105, 122}, {106, 122, 55}, },
     {{48, 95, -23}, {97, 97, 123}, {98, 122, 55}, },
     {{48, 110, -41}, {111, 111, 124}, {112, 122, 55}, },
     {{48, 107, -98}, {108, 108, 125}, {109, 122, 55}, },
     {{48, 100, -30}, {101, 101, 126}, {102, 122, 55}, },
     {{48, 122, -23}, },
     {{101, 101, 127}, {112, 112, 128}, {115, 115, 129}, },
     {{48, 104, -68}, {105, 105, 130}, {106, 122, 55}, },
     {{48, 104, -68}, {105, 105, 131}, {106, 122, 55}, },
     {{48, 95, -23}, {97, 97, 132}, {98, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 122, -23}, },
     {{48, 110, -41}, {111, 111, 133}, {112, 122, 55}, },
     {{48, 113, -69}, {114, 114, 134}, {115, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 115, -27}, {116, 116, 135}, {117, 122, 55}, },
     {{48, 110, -41}, {111, 111, 136}, {112, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 109, -31}, {110, 110, 137}, {111, 122, 55}, },
     {{48, 109, -31}, {110, 110, 138}, {111, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 95, -23}, {97, 103, 55}, {104, 104, 139}, {105, 122, 55}, },
     {{48, 117, -63}, {118, 118, 140}, {119, 122, 55}, },
     {{110, 110, 141}, {115, 115, 142}, },
     {{97, 97, 143}, },
     {{101, 101, 144}, },
     {{48, 110, -41}, {111, 111, 145}, {112, 122, 55}, },
     {{48, 113, -69}, {114, 114, 146}, {115, 122, 55}, },
     {{48, 110, -41}, {111, 111, 147}, {112, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 95, -23}, {97, 97, 148}, {98, 122, 55}, },
     {{48, 95, -23}, {97, 97, 149}, {98, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 116, -36}, {117, 117, 150}, {118, 122, 55}, },
     {{48, 115, -27}, {116, 116, 151}, {117, 122, 55}, },
     {{48, 95, -23}, {97, 97, 152}, {98, 122, 55}, },
     {{48, 95, -23}, {97, 97, 153}, {98, 122, 55}, },
     {{113, 113, 154}, },
     {{99, 99, 155}, },
     {{114, 114, 156}, },
     {{110, 110, 157}, },
     {{48, 122, -23}, },
     {{48, 110, -41}, {111, 111, 158}, {112, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 108, -67}, {109, 109, 159}, {110, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 100, -30}, {101, 101, 160}, {102, 122, 55}, },
     {{48, 110, -41}, {111, 111, 161}, {112, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 122, -23}, },
     {{117, 117, 162}, },
     {{111, 111, 163}, },
     {{97, 97, 164}, },
     {{97, 97, 165}, },
     {{48, 122, -23}, },
     {{48, 95, -23}, {97, 97, 166}, {98, 122, 55}, },
     {{48, 122, -23}, },
     {{48, 122, -23}, },
     {{97, 97, 167}, },
     {{108, 108, 168}, },
     {},
     {{111, 111, 169}, },
     {{48, 122, -23}, },
     {{110, 110, 170}, },
     {{104, 104, 171}, },
     {},
     {{116, 116, 172}, },
     {{97, 97, 173}, },
     {{111, 111, 174}, },
     {},
     {},
     }
     { // COMENTARIO
     {{0, 41, 1}, {42, 42, 2}, {43, 46, 1}, {47, 47, 3}, {48, 65535, 1}, },
     {{0, 41, 1}, {43, 46, 1}, {48, 65535, 1}, },
     {{47, 47, 4}, },
     {{42, 42, 5}, },
     {},
     {},
     }
     };*/

    private static int[][] accept;
    /*  {
     // NORMAL
     {63, 63, 63, 63, 63, 49, 48, 42, 43, 33, 31, 38, 32, 41, 34, 61, 39, 40, 57, 54, 56, 60, 46, 47, 60, 60, 60, 60, 60, 53, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 44, 45, 63, 35, 36, 65, 64, -1, 37, 59, 55, 58, 60, 60, 60, 60, 60, 60, 60, 60, 20, 60, 60, 60, 60, 60, 60, 60, 60, 51, 60, 60, 60, 9, 60, 60, 64, 62, 15, 60, 60, 60, 8, 60, 60, 60, 60, 30, 60, 60, 4, 52, 60, 60, 60, 60, 60, 60, 60, 2, 50, 26, 7, 60, 60, 60, 60, 60, 60, 14, -1, 60, 60, 60, 19, 22, 60, 60, 6, 60, 60, 1, 60, 60, 10, 60, 60, -1, -1, -1, 60, 60, 60, 21, 60, 60, 12, 60, 60, 60, 60, -1, -1, -1, 11, 29, 60, 27, 60, 18, 60, 60, 25, 3, -1, -1, -1, -1, 5, 60, 23, 16, -1, -1, 24, -1, 0, -1, -1, 13, -1, -1, -1, 28, 17, },
     // COMENTARIO
     {66, 66, 67, 68, 69, 65, },

     };*/

    public static class State {

        public final static State NORMAL = new State(0);
        public final static State COMENTARIO = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id) {
            this.id = id;
        }

        public int id() {
            return this.id;
        }
    }

    static {
        try {
            DataInputStream s = new DataInputStream(
                    new BufferedInputStream(
                            Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for (int i = 0; i < gotoTable.length; i++) {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for (int j = 0; j < gotoTable[i].length; j++) {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for (int k = 0; k < gotoTable[i][j].length; k++) {
                        for (int l = 0; l < 3; l++) {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for (int i = 0; i < accept.length; i++) {
                length = s.readInt();
                accept[i] = new int[length];
                for (int j = 0; j < accept[i].length; j++) {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        } catch (Exception e) {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
